global:
  imageRegistry: "docker.io"
  imagePullSecrets: []
  defaultStorageClass: "longhorn"
  security:
    allowInsecureImages: false

# kubeVersion: "1.28"
clusterDomain: "cluster.local"

alertmanager:
  enabled: true
  replicaCount: 3
  configuration: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: 'default-receiver'
    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: 'david.tia@gs2e.ci'
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 20Gi
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: ClusterIP
  networkPolicy:
    enabled: true
    allowExternal: false

server:
  replicaCount: 3
  retention: "30d"
  retentionSize: "50Gi"
  scrapeInterval: "30s"
  evaluationInterval: "30s"
  resources:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 4
      memory: 4Gi
  persistence:
    enabled: true
    storageClass: "longhorn"
    size: 100Gi
  service:
    type: ClusterIP
  logLevel: debug
  enableAdminAPI: false
  extraArgs:
    - "--web.enable-lifecycle"
    - "--storage.tsdb.max-block-duration=2h"
    - "--storage.tsdb.min-block-duration=2h"
  podAntiAffinityPreset: hard
  networkPolicy:
    enabled: true
    allowExternal: false
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false

thanos:
  create: true
  objectStorageConfig:
    secretName: thanos-objstore-config
    secretKey: thanos.yaml
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 2
      memory: 2Gi

# Horizontal Pod Autoscaler via KEDA ou custom HPA si nécessaire
# Cela doit être configuré hors chart ou via kube-prometheus-stack combiné