 # minio-helm-application-argo.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dremio
  namespace: ci-cd
spec:
  project: default
  source:
    repoURL:  https://github.com/AKMADOU/gitops-bigdata.git
    path: dremio
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: analytics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true